#pragma once

#include "IR/Program.h"
#include "Lower/Pass.h"

#include <string>

namespace bonsai {
namespace lower {

// Rewrites exported functions with struct return types to avoid dealing with
// ABI conformance when linking with C++ generated by a standard compiler. For
// example,
//
//   type X = struct { ... }
//   X func foo();
//
//  =>
//
//   $r := build<X>();
//   void foo($r : mut X);
class ReturnToOutParameter : public Pass {
  public:
    constexpr std::string name() const override { return "rtop"; }

    ir::FuncMap run(ir::FuncMap functions) const override;
};

} // namespace lower
} // namespace bonsai
