add_bonsai_tests(
    LABELS lower
    FILES
    adt.bonsai
    adt-layout-inline.bonsai
    adt-layout-per-arm.bonsai
    adt-layout-tagged-index.bonsai
    adt-nested-tagged-index.bonsai
    array.bonsai
    bvh.bonsai
    collision.bonsai
    element-reference-variant.bonsai
    exported-function.bonsai
    extent-after-functions.bonsai
    externs-order.bonsai
    externs-into-recursion.bonsai
    externs-unsized.bonsai
    float.bonsai
    for-sequential.bonsai
    import_externs_use.bonsai
    import_float.bonsai
    import_twice.bonsai
    import_vec3f.bonsai
    index.bonsai
    indirect-group-lookup.bonsai
    ivector.bonsai
    lambda-simple.bonsai
    logical-operation.bonsai
    map-func.bonsai
    match-expr.bonsai
    mixed-tlas.bonsai
    multiple-options.bonsai
    mutual-recursion-extern.bonsai
    negation.bonsai
    nested-exported-function.bonsai
    nested-tree-layout.bonsai
    nested-trees.bonsai
    option-dereference-struct.bonsai
    option-dereference.bonsai
    option-dereference1.bonsai
    option-dereference2.bonsai
    option-nested.bonsai
    option.bonsai
    parse-str.bonsai
    pull-the-ray-back.bonsai
    rect_contains.bonsai
    struct_defaults.bonsai
    tight-array.bonsai
    trace_aosoa.bonsai
    trace.bonsai
    trees.bonsai
    type_coercion_primitive.bonsai
    unswitch.bonsai
    vector-immediate.bonsai
)

add_subdirectory(geomops)
add_subdirectory(setops)
