name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  BUILD_TYPE: Debug

jobs:
  build-and-test:
    # Currently we are only running this on mac-os. For multi-platform:
    # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # There exists an action `KyleMayes/install-llvm-action@v2` that simplifies 
    # this, but as of 29 January 2025, they do not support LLVM19 yet. We resort
    # to manual install à la brew. When transitioning to multi-platform, it'll
    # be nice to rely on this action (hopefully it is updated).
    - name: Install LLVM
      env:
        # https://github.com/Homebrew/brew/issues/14516#issuecomment-1418593313
        HOMEBREW_NO_INSTALL_FROM_API: 1
      run: |
        brew update
        brew install llvm@19

    - name: Add LLVM to PATH
      run: |
        echo "LLVM_ROOT=$(brew --prefix llvm@19)" >> $GITHUB_ENV
        echo "LLVM_CONFIG=$(brew --prefix llvm@19)/bin/llvm-config" >> $GITHUB_ENV
    
    - name: Configure CMake
      run: |
        cmake -S . -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Bonsai
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install runt
      uses: baptiste0928/cargo-install@v3
      with:
        crate: runt
        version: "0.4.1"
      
    - name: Test
      working-directory: ${{ github.workspace }}
      run: runt -d

      # --------
      # Lint the Bonsai C++ code (graciously borrowed from the CIRCT workflow). 
      # We purposefully do this after tests are run so users can quickly iterate.
      # -------

      # Choose the git commit to diff against for the purposes of linting.
      # Since this workflow is triggered on both pushes and pull requests, we
      # have to determine if the pull request target branch is set (which it
      # will only be on the PR triggered flow). If it's not, then compare
      # against the last commit.
    - name: choose-commit
      if: ${{ always() }}
      env:
        # Base ref is the target branch, in text form (not hash)
        PR_BASE: ${{ github.base_ref }}
      run: |
        # Run clang-format
        if [ -z "$PR_BASE" ]; then
          DIFF_COMMIT_NAME="HEAD^"
        else
          DIFF_COMMIT_NAME="$PR_BASE"
        fi
        echo "DIFF_COMMIT_NAME=$DIFF_COMMIT_NAME" >> $GITHUB_ENV

    # Since we did a shallow fetch for this repo, we must fetch the commit
    # upon which we be diff'ing. The last step set the ref name in the
    # $DIFF_COMMIT_NAME environment variable. When running the fetch, resolve
    # it to the commit hash and pass that hash along to subsequent steps.
    - name: git fetch base commit
      continue-on-error: true
      run: |
        if echo "$DIFF_COMMIT_NAME" | grep -q HEAD; then
          DIFF_COMMIT_SHA=$( git rev-parse $DIFF_COMMIT_NAME )
        else
          git fetch --recurse-submodules=no origin $DIFF_COMMIT_NAME
          DIFF_COMMIT_SHA=$( git rev-parse origin/$DIFF_COMMIT_NAME )
        fi
        echo "DIFF_COMMIT=$DIFF_COMMIT_SHA" >> $GITHUB_ENV

    # Run clang-tidy against only the changes. The 'clang-tidy-diff' script
    # does this if supplied with the diff.
    - name: clang-tidy
      working-directory: ${{ github.workspace }}
      run: |
        git update-index --chmod=+x .github/workflows/clang-tidy-diff.py
        if git diff -U0 $DIFF_COMMIT...HEAD | python3 .github/workflows/clang-tidy-diff.py -path build -p1 -fix ; then
          exit 0
        fi
        if git diff --quiet --ignore-submodules; then
          exit 1
        fi
        git clang-format -f $DIFF_COMMIT
        echo "Fixups available for the following files:"
        git diff --ignore-submodules --name-only
        echo "See diff in the clang-tidy.patch artifact."
        git diff --ignore-submodules > clang-tidy.patch
        git checkout .
        exit 1

    # Upload the tidy patches to an artifact (zip'd) associated
    # with the workflow run. Only run this on a failure.
    - name: Upload tidy patches
      uses: actions/upload-artifact@v4
      continue-on-error: true
      if: ${{ failure() }}
      with:
        name: clang-tidy-patches
        path: clang-*.patch

    # Unfortunately, artifact uploads are always zips so display the diff as
    # well to provide feedback at a glance.
    - name: clang tidy patches display
      if: ${{ failure() }}
      continue-on-error: true
      run: |
        if [ ! -z clang-tidy.patch ]; then
          echo "Clang-tidy patch"
          echo "================"
          cat clang-tidy.patch
          echo "================"
        fi