name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  BUILD_TYPE: Debug

jobs:
  # TODO(cgyurgyik): Run clang-format, clang-tidy. (The CIRCT project has this set up.)
  build-and-test-Bonsai:
    # Currently we are only running this on mac-os. For multi-platform:
    # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "19.1.6"
        directory: ${{ runner.temp }}/llvm

    - name: Build Bonsai
      run: |
        export LLVM_ROOT=${{ env.LLVM_PATH }}
        export LLVM_CONFIG=$LLVM_ROOT/bin/llvm-config
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install runt
      uses: baptiste0928/cargo-install@v3
      with:
        crate: runt
        version: "0.4.1"
      
    - name: Test
      working-directory: ${{github.workspace}}
      run: runt -d
